# Generated by Django 4.0.4 on 2022-05-30 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ManagementProduct',
            fields=[
                ('product_id', models.CharField(max_length=30, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=250)),
                ('category', models.CharField(max_length=60)),
                ('description', models.TextField(blank=True, max_length=250, null=True)),
                ('price', models.IntegerField()),
                ('stock', models.IntegerField()),
                ('date', models.DateTimeField(auto_now=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='images/')),
            ],
        ),
    ]
