# Generated by Django 4.0.4 on 2022-05-30 05:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('productManagement', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sale_detail',
            fields=[
                ('sales_detail_id', models.AutoField(primary_key=True, serialize=False)),
                ('quantity', models.IntegerField(default=1)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='productManagement.managementproduct')),
            ],
        ),
        migrations.CreateModel(
            name='Sale',
            fields=[
                ('sales_id', models.AutoField(primary_key=True, serialize=False)),
                ('voucher_type', models.CharField(max_length=100)),
                ('date', models.DateTimeField(auto_now=True)),
                ('tax', models.DecimalField(decimal_places=2, max_digits=6)),
                ('total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
