# Generated by Django 4.0.4 on 2022-05-30 05:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('productManagement', '0001_initial'),
        ('ecommerce', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='products',
            field=models.ManyToManyField(related_name='products', through='ecommerce.Sale_detail', to='productManagement.managementproduct'),
        ),
        migrations.AddField(
            model_name='sale_detail',
            name='sales',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='ecommerce.sale'),
            preserve_default=False,
        ),
    ]
